=== bnggge/edtf-converter/src/i18n/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "locale": {
      "type": "string"
    },
    "dateFormats": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "keywords": {
      "type": "object",
      "properties": {
        "approximate": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "uncertain": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "interval": {
          "properties": {
            "delimiters": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "startOpen": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "endOpen": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "seasons": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "minItems": 1
      },
      "minItems": 4,
      "maxItems": 4
    }
  },
  "additionalProperties": false
}

=== bnggge/edtf-converter/src/i18n/en.json
{
  "$schema": "./schema.json",
  "locale": "en",
  "dateFormats": ["DD/MM/YYYY", "MM/YYYY", "YYYY", "MMM Do YYYY", "MMMM Do YYYY", "MMM YYYY", "MMMM YYYY"],
  "keywords": {
    "approximate": ["c.", "ca.", "ca", "circa", "approx", "near", "around", "about"],
    "uncertain": ["maybe", "possibly"],
    "interval": {
      "delimiters": ["to", "until"],
      "startOpen": ["before", "until"],
      "endOpen": ["after", "from", "since", "as of"]
    }
  },
  "seasons": [
    ["spring"],
    ["summer"],
    ["autumn", "fall"],
    ["winter"]
  ]
}
